# Generated by Django 4.0.6 on 2023-06-06 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
