# Generated by Django 4.0.6 on 2023-06-07 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_product_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
