# Generated by Django 4.0.6 on 2023-06-07 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_alter_product_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_date",
        ),
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
