# Generated by Django 4.2.2 on 2023-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_orderitem_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="address",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
    ]
