# Generated by Django 4.2.2 on 2023-06-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0008_alter_orderitem_address_alter_orderitem_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
        ),
    ]
